<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
?>
<div class="col-md-12">
    <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
    <?php $this->trigger('view.show.before'); ?>
    <?php if ($this->themeSetting('uv_item_show') == 'top'): ?>
        <div id="viewer-top"></div>
    <?php endif; ?>
</div>
<div class="col-md-9 offset-md-1-5">
    <div class="main-content-container">
<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-embeds">
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>
<h2 class="metadata-header">Descriptive Information</h2>
<div class="property">
    <h4><?php echo $translate('Permalink'); ?></h4>
    <div class="values">
        <div class="value">
            <?php echo $item->siteUrl($siteSlug = null, $canonical = true); ?>
        </div>
    </div>
</div>
<?php echo $item->displayValues(); ?>
<div class="property">
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
    <h4><?php echo $translate('Item sets'); ?></h4>
    <?php foreach ($itemSets as $itemSet): ?>
    <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
    <?php endforeach; ?>
    <?php endif; ?>
</div>
<?php if (!$embedMedia && $itemMedia && !$this->themeSetting('media_list')): ?>
<div class="property">
    <h4><?php echo $translate('Item Media'); ?></h4>
    <ul class="media-list">
        <?php foreach ($itemMedia as $media): ?>
            <li><?php echo $media->linkPretty(); ?></li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>
    </div>
</div>
<div class="col-md-12">
<?php if ($this->themeSetting('uv_item_show') == 'bottom'): ?>
    <div id="viewer-bottom"></div>
<?php elseif ($this->themeSetting('uv_item_browse') == 'off'): ?>
    <div id="viewer-off"></div>
<?php endif; ?>
<?php $this->trigger('view.show.after'); ?>
</div>
