<?php
$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>
<div class="col-md-9 offset-md-1-5">
    <div class="main-content-container">
    <?php echo $this->pageTitle($media->displayTitle(), 2); ?>
    <h3><?php echo $translate('Media'); ?></h3>
    <?php $this->trigger('view.show.before'); ?>
    <?php echo $media->render(); ?>
    <?php echo $media->displayValues(); ?>
    <?php $this->trigger('view.show.after'); ?>
    </div>
</div>
