<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<div class="resource-list preview">
<?php
$showThumbnail = in_array('thumbnail', $this->components);
$showHeading = in_array('resource-heading', $this->components);
$showBody = in_array('resource-body', $this->components);
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
