<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<div class="resource-list preview">
<?php
$showThumbnail = in_array('thumbnail', $this->components);
$showHeading = in_array('resource-heading', $this->components);
$showBody = in_array('resource-body', $this->components);
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$options = array();
$viewName = 'common/publications/catalog-index';
$title = '';
$authors = '';
$blurb = '';

//resource properties are indexed by the property's term
if ($this->themeSetting('browse_preview_title')) {
    $property = $this->api()->read('properties', ['id' => $this->themeSetting('browse_preview_title')]);
    if ($property) {
        $title = $property->getContent()->term();
    }
}
if ($this->themeSetting('browse_preview_author')) {
    $property = $this->api()->read('properties', ['id' => $this->themeSetting('browse_preview_author')]);
    if ($property) {
        $title = $property->getContent()->term();
    }
}

if ($this->themeSetting('browse_preview_description')) {
    $property = $this->api()->read('properties', ['id' => $this->themeSetting('browse_preview_description')]);
    if ($property) {
        $blurb = $property->getContent()->term();
    }
}

$options =
    [
        'viewName' => $viewName,
        'title' => $title,
        'authors' => $authors,
        'blurb' => $blurb,
    ];

?>
    <div class="container">
        <div class="row">
    <?php foreach ($this->resources as $resource): ?>
        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top" src="<?php echo $resource->primaryMedia()->thumbnailUrl('square') ?>" alt="Card image cap">
                <div class="card-body">
                    <?php echo $resource->displayValues($options) ?>
                </div>
            </div>
        </div>

<?php endforeach; ?>
    </div>
    </div>

