<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>

<?php if ($this->heading): ?>
<h2 class="toc-card-header"><?php echo $this->heading; ?></h2>
<?php endif; ?>

<div class="resource-list preview">
<?php
$showThumbnail = in_array('thumbnail', $this->components);
$showHeading = in_array('resource-heading', $this->components);
$showBody = in_array('resource-body', $this->components);
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$pub_template = $this->themeSetting('publication_template');
$author_template = $this->themeSetting('author_template');
$options = array();

//determine if this browse preview is for one of the special templates
if (array_key_exists('resource_template_id', $query) && count($query['resource_template_id']) == 1) {
    if ($query['resource_template_id'][0] == $pub_template) {
        $options['viewName'] = 'common/publications/index';
    } elseif ($query['resource_template_id'][0] == $author_template) {
        $options['viewName'] = 'common/authors/index';
    }
}

$count = 2;
?>
    <?php foreach ($this->resources as $resource): ?>

<?php endforeach; ?>

    </div>
    </div>

<?php $count = 0; ?>

<div class="container">
    <?php foreach ($resources as $resource): ?>
        <?php $thumbnail = $this->assetUrl('img/Placeholder.png'); ?>
        <?php $alt = '' ?>
        <?php  $count+=1 ?>
        <?php if ($count%2): ?>
            <div class="row">
        <?php endif; ?>

        <div class="col-lg-6 mb-4">
            <div class="card mb-3 toc-card " style="max-width: 540px; background: #E8E9EB;" >
                <div class="row g-0 toc-row">
                    <div class="col-md-4">
                        <?php if ($resource->primaryMedia()): ?>
                            <?php
                            $thumbnail = $resource->primaryMedia()->thumbnailUrl('large');
                            $alt = 'alt="' . $resource->primaryMedia()->altText() . '"'
                            ?>
                        <?php endif; ?>
                        <a href="<?php echo $resource->siteUrl() ?>"> <img src="<?php echo $thumbnail ?>" class="img-fluid rounded-start" <?php echo $alt ?>></a>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body" style="border: none">
                            <?php echo $resource->displayValues($options) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php if ($count % 2 == 0): ?>
            </div>
    <?php endif; ?>
<?php endforeach; ?>

    <?php if ($count % 2): ?>
</div>
<?php endif; ?>
</div>