<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
//$this->headLink()->appendStylesheet('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css');
$this->headLink()->prependStylesheet($this->assetUrl('css/bootstrap.css'));
$this->headScript()->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js');
$this->headScript()->prependFile('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js');

$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>

        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }

            a:active,
            a:hover {
                color: <?php echo darken_color($accentColor, 20); ?>;
            }

            .toc-card:hover a, .toc-card:hover .card-title {
                color: <?php echo darken_color($accentColor, 20); ?>;
            }

            .toc-card .card-title {
                color: <?php echo $accentColor; ?>;
            }
            <?php endif; ?>
            <?php if ($this->themeSetting('nav_items')): ?>
            ul.navigation > li:nth-child(n+<?php echo $this->themeSetting('nav_items') + 1; ?>){
                display:none;
            }
            <?php endif;?>
        </style>
    </head>

<?php echo $this->htmlElement('body'); ?>
<?php echo $userBar; ?>
    <header>
        <?php if ($this->themeSetting('banner')): ?>
            <div class="col-sm-12 banner" style="background-image:linear-gradient(rgba(0,0,0,.4), rgba(0,0,0,.4)), url('<?php echo $this->themeSettingAssetUrl('banner');?>')">
                <div id="search">
                    <?php echo $this->partial('common/search-form'); ?>
                </div>
                <div class="site-title">
                    <a href="<?php echo $site->url(); ?>" class="site-title"><h1><?php echo $escape($siteTitle); ?></h1></a>
                </div>
                <div class="banner-caption"><?php echo $this->themeSetting('banner_caption');?></div>
            </div>
        <?php else: ?>
            <div class="col-sm-12 banner" style="background-image:linear-gradient(rgba(0,0,0,.4), rgba(0,0,0,.4)), url('<?php echo $this->assetUrl('img/Default-header.jpg') ?>')">
                <div id="search">
                    <?php echo $this->partial('common/search-form'); ?>
                </div>
                <div class="site-title">
                    <a href="<?php echo $site->url(); ?>" class="site-title"><h1><?php echo $escape($siteTitle); ?></h1></a>
                </div>
                <div class="banner-caption">University of Illinois Main Library, courtesy of <a href="https://commons.wikimedia.org/wiki/File:Main_Library-University_of_Illinois_at_Urbana-Champaign_09.jpg">Killivalavan Solai, Wikimedia Commons</a></div>
            </div>
        <?php endif; ?>

        <nav>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
        </nav>
    </header>
    <div role="main" class="container-lg">
        <?php echo $this->content; ?>
    </div>
    <footer>
        <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
        <?php endif; ?>
    </footer>
    </body>
    </html>
<?php

function darken_color($hex, $percent)
{
    preg_match('/^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i', $hex, $primary_colors);
    str_replace('%', '', $percent);
    $color = "#";
    for ($i = 1; $i <= 3; $i++) {
        $primary_colors[$i] = hexdec($primary_colors[$i]);
        $primary_colors[$i] = round($primary_colors[$i] * (100-($percent*2))/100);
        $color .= str_pad(dechex($primary_colors[$i]), 2, '0', STR_PAD_LEFT);
    }

    return $color;
}
