<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
if ($this->status()->isSiteRequest()) {
    $showLocale = (bool) $this->siteSetting('show_locale_label', true);
    $filterLocale = $this->siteSetting('filter_locale_values');
    $lang = $this->lang();
    $showValueAnnotations = (bool) $this->siteSetting('show_value_annotations', false);
} else {
    $showLocale = true;
    $filterLocale = false;
    $lang = null;
    $showValueAnnotations = true;
}
?>
<?php if ($title && array_key_exists($title, $values)): ?>
    <div class="card-title"><p><?php echo $values[$title]['values'][0] ?></p></div>
<?php endif; ?>

<!--design supports multiple authors-->
<?php if ($authors && array_key_exists($authors, $values) ): ?>
    <?php if (count($values[$authors]['values']) >= 6): ?>
        <div class="card-subtitle"><?php echo $values[$this->authors]['values'][0]->valueResource()->displayTitle() ?>, et al. </div>
    <?php else: ?>
        <ul class="resource-list">
        <?php foreach ($values[$this->authors]['values'] as $author): ?>
            <li class="item"> <a href="<?php echo $author->valueResource()->url() ?>"> <?php echo $author->valueResource()->title() ?></a></li>
            </ul>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>

<?php if ($blurb && array_key_exists($blurb, $values)): ?>
    <div class="card-text"><?php echo $values[$blurb]['values'][0]?> </div>
<?php endif; ?>
